version: 0.5.5-{build}

branches:
  except:
    - doc

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\checksums

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="x86_64-pc-windows-gnu"

build: off
build_script:
  - git submodule update --init --recursive
  - cargo build --verbose --release
  - cp target\release\checksums.exe checksums-v0.5.5.exe
  - strip --strip-all --remove-section=.comment --remove-section=.note checksums-v0.5.5.exe

test: off
test_script:
  - cargo test --verbose --release
  - target\release\checksums -cr --ignore target --ignore .git && cat checksums.hash

artifacts:
  - path: checksums-v0.5.5.exe

deploy:
  provider: GitHub
  artifact: checksums-v0.5.5.exe
  auth_token:
    secure: zc/M0k0pSOFA3H9GhgTOFhYmOj6M88rfqwfjDhvhlzz/oa8P9JL+7XR4LmDHajJp
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
